spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
      name: auth-server
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    username: root
    password: root
  redis:
    host: 127.0.0.1

server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

ignore:
  urls:
   - /uaa/**
   - /swagger-resources/**
   - /swagger-ui.html
   - /*/v2/api-docs
   - /swagger/api-docs
   - /webjars/**