server:
  port: 7000
spring:
  application:
    name: auth
#  datasource:
#    url: jdbc:mysql://localhost:3306/hsm?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: root
#    driverClassName: com.mysql.jdbc.Driver
#    dbcp2:
#      max-idle: 5
#      max-wait-millis: 10000
#      min-idle: 2
#      initial-size: 3
#      validation-query: SELECT 1
#      time-between-eviction-runs-millis: 18800
#    tomcat:
#      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=50)
  redis:
    database: 0
    host: localhost
    password:
    timeout: 3000
    port: 6379
    jedis:
      pool:
        max-active: 5
        min-idle: 0
        max-wait: 1
        max-idle: 8
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: static-${server.port}
        uri: http://zhangzhg.oss-cn-hangzhou.aliyuncs.com/
        predicates:
        - Path=/static/**
        filters:
        - StripPrefix= 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

security:
  user: zzg123456
  oauth2:
    sso:
      loginPath: /login   # 登录路径
    client:
      clientId: 430a12f4a52a5eeba8dc
      clientSecret: b4c5abd9362cf058ea2cb4275fee752ecfde02cc
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false