server:
  port: 8080

spring:
  application:
    name: cloud-gateway
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    username: root
    password: root

zuul:
  routes:
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: auth-server
    core:
      path: /core/**
      sensitiveHeaders:
      serviceId: core
  add-proxy-headers: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
      clientId: gateway
      clientSecret: secret
    resource:
      userInfoUri: http://localhost:8080/uaa/user
      preferTokenInfo: false