server:
  port: 9000
  servlet:
      context-path: /order
spring:
  application:
    name: order
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false

security:
  oauth2:
    resource:
      id: order
      user-info-uri: http://localhost:8080/uaa/user
      prefer-token-info: false

logging.level.org.springframework.security: DEBUG