server:
  port: 8081

spring:
  application:
    name: zipkin-server
  # 监控百分比 1.0 监控所有
  zipkin:
    base-url: http://localhost:8081
    sleuth:
      sampler:
      percentage: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
# 解决报错问题
management:
  metrics:
    web:
      server:
        auto-time-requests: false

