spring:
  jpa:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      show-sql: true
      format-sql: true
      hibernate:
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      entity-package: com.**.model
mybatis:
  mapper-locations: "classpath*:mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true